### ISSUE TITLE
Create a ShopsToPrices cannabis product dropdown klopt niet.

### ISSUE THREAD

**Issue by azxxl** [acidjunk/pricelist-admin#33]
Als je een prijs aan een shop wilt toevoegen dan toont de Cannabis product dropdown een ongesorteerde lijst met cannabis producten.

![ScreenshotAdminInterfaceCannabis-Dropdown](https://user-images.githubusercontent.com/64080426/168853069-7d4e1571-124f-40bd-b847-4a356d5014f5.jpg)

**Comment by acidjunk** [comment]
Gebruik de autocomplete. Hij laat inderdaad een stuk 10 by default zien. (sort op ID)
