### ISSUE TITLE
Afbeelding verwijderen

### ISSUE THREAD

**Issue by azxxl** [acidjunk/pricelist-admin#7]
Ik krijg een foutmelding als ik een afbeelding wil verwijderen bij een product (zie screenshot)

![ScreenshotDeleteImage](https://user-images.githubusercontent.com/64080426/87456081-b4952c80-c606-11ea-8734-7ab96b474a2d.jpg)

Krijg voor de rest geen melding in de console.

Script: ProductImages.jsx

**Comment by acidjunk** [comment]
Dat klopt: delete is nog niet geïmplementeerd voor plaatjes: maar dat weet de admin niet.

Lage prio: niet blocking voor livegang

**Comment by acidjunk** [comment]
Djuh: deze issue staat nu in public repo

**Comment by acidjunk** [comment]
Is ca jaar terug gefixed.
